### ISSUE TITLE
ValueError: sequence too large

### ISSUE THREAD

**Issue by afrahshafquat** [cagatayyildiz/npde#3]
Hello, the dataset dimensions are Y (1, 2244, 569), and t(1, 2244), however when I run the following command, I get the following error:

>>> npde = npde_fit(sess, t, Y, model='sde', W=1.0058, ktype="id", fix_Z=True, Nw=10, num_iter=100, print_int=100, eta=0.02, plot_=True, ell0=np.ones(569), ellg0=[1e5])
Model being initialized...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/athena/mezeylab/scratch/as3397/npde/npde_helper.py", line 80, in npde_fit
    vecs = np.meshgrid(*grids)
  File "/home/as3397/.conda/envs/tf-gpu2/lib/python3.5/site-packages/numpy/lib/function_base.py", line 4048, in meshgrid
    for i, x in enumerate(xi)]
  File "/home/as3397/.conda/envs/tf-gpu2/lib/python3.5/site-packages/numpy/lib/function_base.py", line 4048, in <listcomp>
    for i, x in enumerate(xi)]
ValueError: sequence too large; cannot be greater than 32

Do you have any idea why this might be happening?

**Comment by cagatayyildiz** [comment]
The problem is related to the initialization of inducing locations. My implementation creates a grid of inducing locations, which is suitable for small-scale problems. I'd suggest you perform k-means on your training data and set the cluster centers as the initial inducing locations.
