### ISSUE TITLE
turning off the true path in plotting

### ISSUE THREAD

**Issue by afrahshafquat** [cagatayyildiz/npde#4]
Hello,
I am getting the following error, I believe its because of the "true path plotting". Is there an option to turn it off? Thanks so much.

>>> npde = npde_fit(sess, t, Y, model='sde', sf0=1.0, ell0=np.ones(5, dtype=np.float64), ellg0=[1.0], W=2, ktype="id", 
...                 fix_Z=True, Nw=200, num_iter=500, print_int=100, eta=0.01, plot_=True)
Model being initialized...
Adam optimizer being initialized...
Optimization starts.
       iteration       objective
               1       34633.532
             100       30749.023
oh yeah              200       29533.534
             300       28658.060
             400       27934.877
             500       27265.514
Optimization ends.
Plotting...
noise variance:        [1.60207482 1.05628679 1.09402518 1.21820736 1.53764724]
signal variance:       0.6738406245387211
lengthscales:          [0.36330872 0.77718864 0.68213066 0.60997537 0.37128257]
diff signal variance:  2.7179468499240924
diff lengthscales:     [2.82314066]
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/athena/mezeylab/scratch/as3397/npde/npde_helper.py", line 184, in npde_fit
    plot_model(npde,Nw=50)
  File "/athena/mezeylab/scratch/as3397/npde/utils.py", line 87, in plot_model
    true_path = em_int(vdp,g,npde.x0[0,:],vdpts)
  File "/athena/mezeylab/scratch/as3397/npde/utils.py", line 64, in em_int
    Xs[i+1,:] = Xs[i,:] + fdt + gdt.flatten()
ValueError: operands could not be broadcast together with shapes (5,) (2,)

**Comment by cagatayyildiz** [comment]
The demo code works fine on my laptop. Could you elaborate on what you're trying? In worst scenario, you could just comment out true path visualization.
